# Generated by Django 5.2.7 on 2025-10-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_device_is_written_off_device_responsible_person_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="equipmentmovement",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "Движение оборудования",
                "verbose_name_plural": "Движения оборудования",
            },
        ),
        migrations.AlterField(
            model_name="equipmentmovement",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("issue", "Выдача"),
                    ("return", "Возврат"),
                    ("repair", "Передача в ремонт"),
                    ("write_off", "Списание"),
                ],
                max_length=20,
            ),
        ),
    ]
