# Generated by Django 5.2.7 on 2025-10-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_employee_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="ai_needs_clarification",
            field=models.BooleanField(
                default=False,
                help_text="Заявка требует дополнительных уточнений по мнению AI",
                verbose_name="AI: Требует уточнений",
            ),
        ),
        migrations.AddField(
            model_name="request",
            name="ai_priority_score",
            field=models.FloatField(
                blank=True,
                help_text="1 (низкий) - 10 (критичный)",
                null=True,
                verbose_name="AI Оценка приоритета",
            ),
        ),
        migrations.AddField(
            model_name="request",
            name="ai_summary",
            field=models.TextField(
                blank=True,
                help_text="Краткое описание проблемы от AI",
                verbose_name="AI Резюме",
            ),
        ),
        migrations.AddField(
            model_name="request",
            name="ai_tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Автоматические теги от AI",
                verbose_name="AI Теги",
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="purpose",
            field=models.TextField(verbose_name="Цель использования"),
        ),
    ]
